---
defaults:
  domain: empire.space
  contact: Unknown

8k_routers:
  username: cisco
  password: cisco123
  nornir_nos: iosxr
  contact: Router team
  platform: iosxr_netconf
  ssh_config:
    ignore_unknown_hosts: True
  data:
    xr_7: True
    target_os_ver: 7.9.2
    image_file: 8000-x64-7.9.2.iso
    http_server_ip: 192.168.122.251
    install_commands:
      - command: "install replace /harddisk:/8000-x64-7.9.2.iso noprompt reload commit synchronous"
        reload: True

9k_routers:
  username: cisco
  password: cisco123
  nornir_nos: iosxr
  contact: Router team
  platform: iosxr_netconf
  ssh_config:
    ignore_unknown_hosts: True
  data:
    xr_7: True
    target_os_ver: 7.9.2
    image_files:
      - asr9k-mini-x64-7.9.2.iso # upgrade id 0
    http_server_ip: 192.168.122.251
    install_commands:
      - command: "install add source /harddisk: /asr9k-mini-x64-7.9.2.iso synchronous"
        reload: False
      - command: "install activate asr9k-mini-x64-7.9.2 noprompt synchronous"
        reload: True
      - command: "install commit synchronous"
        reload: False