---
defaults:
  domain: empire.space
  contact: Unknown

8k_routers:
  username: cisco
  password: cisco123
  nornir_nos: iosxr
  contact: Router team
  platform: iosxr_netconf
  ssh_config:
    ignore_unknown_hosts: True
  data:
    xr_7: True
    target_os_ver: 7.9.2
    copy_command: "copy tftp://192.168.122.162/8000-x64-7.9.2.iso harddisk:"
    install_commands:
      - command: "install replace /harddisk:/8000-x64-7.9.2.iso noprompt reload commit synchronous"
        reload: True
    pre_check_commands:
      - "show platform"
      - "show inventory"
      - "show version"
      - "show interface description"
      - "show interface summary"
      - "show ipv4 interface brief"
      - "show ipv6 interface brief"
      - "show bgp all all summary"
      - "show isis neighbor"
      - "show isis adjacency"
      - "show mpls ldp int brief"
      - "show mpls forwarding"
      - "show mpls ldp neighbor"
      - "show mpls ldp summary"
      - "show mpls ldp bindings"
      - "show mpls interface"
      - "show run mpls traffic-eng"
      - "show l2vpn xconnect"
      - "show l2vpn bridge-domain"
      - "show pim neighbor"
      - "show pim topology"
      - "show route ipv4 summary"
      - "show route ipv6 summary"
      - "show cef summary"
      - "show lldp neighbor"
      - "show mrib route summary"
      - "show mrib route"
      - "show mfib route rate"

9k_routers:
  username: cisco
  password: cisco123
  nornir_nos: iosxr
  contact: Router team
  platform: iosxr_netconf
  ssh_config:
    ignore_unknown_hosts: True
  data:
    xr_7: True
    target_os_ver: 7.9.2
#    copy_command: "copy tftp://192.168.122.162/asr9k-full-x64-7.9.2.iso harddisk:"
    copy_command: "scp vxr@192.168.122.121://home/vxr/asr9k-full-x64-7.9.2.iso /misc/disk1/."
    install_commands:
#      - command: "install replace /harddisk:/asr9k-full-x64-7.9.2.iso"
#        reload: True
      - command: "install add source /harddisk: asr9k-full-x64-7.9.2.iso synchronous"
        reload: False
      - command: "install activate asr9k-full-x64-7.9.2 noprompt synchronous"
        reload: True
      - command: "install commit synchronous"
        reload: False
    pre_check_commands:
      - "show platform"
      - "show inventory"
      - "show version"
      - "show interface description"
      - "show interface summary"
      - "show ipv4 interface brief"
      - "show ipv6 interface brief"
      - "show bgp all all summary"
      - "show isis neighbor"
      - "show isis adjacency"
      - "show mpls ldp int brief"
      - "show mpls forwarding"
      - "show mpls ldp neighbors"
      - "show mpls ldp summary"
      - "show mpls ldp bindings"
      - "show mpls interface"
      - "show run mpls traffic-eng"
      - "show l2vpn xconnect"
      - "show l2vpn bridge-domain"
      - "show pim neighbor"
      - "show pim topology"
      - "show route ipv4 summary"
      - "show route ipv6 summary"
      - "show cef summary"
      - "show lldp neighbor"
      - "show mrib route summary"
      - "show mrib route"
      - "show mfib route rate"